services:
  db:
    image: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql:Z

volumes:
  db_data: